import numpy as np
from sklearn.ensemble import IsolationForest
import pickle
import pandas as pd


def iso_forest(key_points):
    """
    Creates an Isolation Forest model on training processed key points.

    :param key_points: Numpy array of key points
    """
    iso = IsolationForest(max_features=50, behaviour='new').fit(key_points)
    filename = 'gait_analysis_model_iso_ec2.sav'
    pickle.dump(iso, open(filename, 'wb'), protocol=2)
    print("Done")


def preprocess(data_unprocessed):
    """
    Prepossesses data to remove confidence scores generated by OpenPose
    :param data_unprocessed: Unprocessed data from training.csv file
    """
    remove_data = [x for x in range(3601) if x % 3 == 2]
    data_processed = np.delete(data_unprocessed, remove_data, 1)
    return data_processed


if __name__ == '__main__':
    data = pd.read_csv("training.csv", dtype=np.dtype('float64'), names=list(range(3600)))
    data = data.fillna(0)
    data = data.to_numpy()
    data = preprocess(data)
    iso_forest(data)
